### ISSUE TITLE
No `*rc` (.stylelintrc.json, .eslintrc.yml & etc.) icon added when using file extensions

### ISSUE THREAD

**Issue by tomahl** [oivva/sublime-file-icons#48]
If you name the configuration file other than default (.stylelintrc) no Stylelint icon is added.

As a user I would like to be able to use the alternative names (stylelint.config.js, .stylelintrc.json, .stylelintrc.yaml, .stylelintrc.js) and still get the new Stylelint icon so that it doesn't get mixed up with other .js, .json or .yaml files.

**Comment by oivva** [comment]
Ok, that's discussed [here](https://github.com/oivva/sublime-file-icons/issues/5). It's nothing for me to add the icon, however we are always trying to minimize syntax alias abuse. So I think we left this for voting.

**Comment by oivva** [comment]
👍 - for adding icons for such files `stylelint.config.js`, `.stylelintrc.json`, `.eslintrc.yml`, `.eslintrc.json` and etc.
👎 - add icons only for `.stylintrc`, `.eslintrc` and etc.

**Comment by r3nya** [comment]
I think that it's good idea. :)

**Comment by tomahl** [comment]
It would be nice to be able to tell the difference between "settings" files (gulp, grunt, es-lint, stylelint etc) from end-product files that will be hosted on the server.

**Comment by oivva** [comment]
I'll add option to disable all syntax aliases, that's why if the user doesn't like `.stylelintrc.json` icon `json` icon will be used instead.
