### ISSUE TITLE
ColdFusion icon

### ISSUE THREAD

**Issue by ivanionut** [oivva/sublime-file-icons#49]
Hi,
you can add the icon for coldfusion file _(.cfm and .cfc)_?

Thank you!

**Comment by ivanionut** [comment]
oh, sorry. Now I have seen that there exists... But it is not for nothing readable. 😭

**Comment by r3nya** [comment]
@ivanionut hey! Can you create a screenshot? :)

**Comment by ivanionut** [comment]
I did not understand what it meant... I thought it was written "C+" 😄 
![cfc files](https://hostr.co/file/4nya9CUv4AbV/cf.png)

**Comment by oivva** [comment]
@ivanionut See [required packages](https://github.com/oivva/sublime-file-icons/blob/dev/PACKAGES.md#cold-fusion) to install for `.cfm` & `.cfc`.
