### ISSUE TITLE
Add missing alias for Dockerfile

### ISSUE THREAD

**Issue by mikhail-angelov** [oivva/sublime-file-icons#52]
please add icons for docker files
- Dockerfile
- docker-compose.yml

add icons for files .tag (http://riotjs.com)
- *.tag

**Comment by r3nya** [comment]
@mikhail-angelov hello mate! :)

**Comment by r3nya** [comment]
### TODO

[ ] `docker-compose.yml`
[ ] `*.tag` files for http://riotjs.com
